### PR TITLE
fix(build): trailing comma preventing parsing with jq

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

This fixes the following [error happening during the iOS build](https://github.com/valora-inc/release-automation/actions/runs/8045843098/job/21971906062):
```
[08:38:58]: ▸ + /opt/homebrew/bin/jq -r '.mainnet|to_entries|map("\(.key)=\(.value|tostring)")|.[]' /Users/runner/work/release-automation/release-automation/wallet/ios/../secrets.json
[08:38:58]: ▸ jq: parse error: Expected another key-value pair at line 18, column 3
```

The problem was introduced in https://github.com/valora-inc/wallet/pull/4942

### Test plan

iOS build works again.

### Related issues

N/A

### Backwards compatibility

Yes

### Network scalability

If a new NetworkId and/or Network are added in the future, the changes in this PR will:

- [x] Continue to work without code changes, OR trigger a compilation error (guaranteeing we find it when a new network is added)

### CODE REVIEW

**Review by kathaypacific — APPROVED** [review]

**Review by bakoushin — APPROVED** [review]
🙏 Thanks for fixing this!
